### ISSUE TITLE
new textures

### ISSUE THREAD

**Issue by Sigma88** [Poodmund/PoodsOPMVO#1]
hi pood, I can't seem to find the new textures.
if you have problems uploading them to my github just send me a link to the images in your github repository.

btw, I just need the base urlum texture, I can tilt it myself :)

if you have any issues just let me know

**Comment by Poodmund** [comment]
Sorry, had a chronic migraine last night so shot off quick. Created a pull request for the changes for Tilt on your repo. Will do Recolour in a bit.

EDIT: Can't seem to figure out how you modified the base textures for your recolour mod, my textures can be found here: https://www.dropbox.com/s/xgt2d2x4ua6s92o/PoodTextures.rar?dl=0

**Comment by Poodmund** [comment]
Resolved in latest dev builds of OPM-Tilt and OPM-Recolour.

Issue closed.
