### ISSUE TITLE
No Clouds on Tekto

### ISSUE THREAD

**Issue by MarkSaint** [Poodmund/PoodsOPMVO#2]
Clouds don't appear on Tekto, as discussed in the development thread. I've attached the log file. 
[KSP.txt](https://github.com/Poodmund/PoodsOPMVO/files/212073/KSP.txt)

**Comment by Andem6** [comment]
I haven't seen any either :/
Trying to find the last official RELEASE in order to find out what EVE .it uses, but there are only prereleases. I'll do my best to help until Poods checks his Github.

**Comment by Poodmund** [comment]
I am not sure how the current Pre-Releases will work in 1.1 as they were built for 1.0.5 with a EVE build for 1.0.5 also. I would say at this point please be patient as I will be looking to release a 1.1 compatible release of this mod once the other dependent mods are released for 1.1 also.

Have faith. :D

**Comment by Poodmund** [comment]
New build released for KSP 1.1.2. Try grabbing all the latest versions of Module Manager, Kopernicus, EVE, Scatterer and OPM and see if the problem still persists.
